name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  do-it:
    runs-on: ubuntu-latest
    
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 10s
      
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s

  calling_another_workflow:   
    uses: Aish1999/Reusable_workflow/.github/workflows/actions.yml@main

