name: Main Workflow

on:
    workflow_dispatch:
     inputs:
      CICD workflow:
        description: 'Ù‹Workflow 2 which will be triggered'
        required: true
        default: 'CICD workflow'

      workflow2_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: ':Aish19999'

      workflow2_repo_github:
        description: 'Reusable_workflow'
        required: true
        default: ':Reusable_workflow'
    push:
      branches:
      - main
  
  
jobs:
  read_config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Call Another Workflow
        run: |
          # Execute another workflow using its workflow name
          curl -X POST https://api.github.com/repos/Aish19999/Reusable_workflow/actions/workflows/actions.yml/dispatches \
            -H "Authorization: token ${{ secrets.ACTIONS_KEY }}" \
            -d '{
               "ref": "main"
              }' 
      - uses: actions/checkout@v3      
