name: My Custom Workflow

on:
  workflow_call:
  workflow_run:
    workflows: ["Main Workflow"]
    types:
      - completed
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: check env varaible
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
          ACTIONS_STEP_DEBUG: true
        run: |
          PAT="${{ env.WORKFLOW_PAT }}" 
          echo "My PAT Token: $PAT"

  pipeline:
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout code
        uses: actions/checkout@v2   
        
      - name: Dynamically Call Workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
          ACTIONS_STEP_DEBUG: true

        run: |
          PAT="${{ env.WORKFLOW_PAT }}" 
          echo "My PAT Token: $PAT"
      
